zuuu_hal:
  ros__parameters:
    laser_upper_angle: 2.6
    laser_lower_angle: -2.6
    max_duty_cyle: 0.1 # max is 1.0
    cmd_vel_timeout: 0.2
    max_full_com_fails: 100
    main_tick_period: 0.012
    control_mode: "OPEN_LOOP"
    max_accel_xy: 1.0
    max_accel_theta: 1.0
    xy_tol: 0.0
    theta_tol: 0.0
    smoothing_factor: 5.0
